#ouvre la configuration globale
server {
# écoute le port par défaut
    listen 80;

#règle la page d'accueil principale
    location / {
#indique l'emplacement des fichiers html
        root /usr/share/nginx/html;
#charge le document d'entrée
        index index.html;
#ferme la règle de l'accueil
    }

#intercepte la navigation vers le jeu
    location /jeu-1-two-ships/ {
#route le trafic vers la machine du jeu
        proxy_pass http://jeu-1:80/;
#clôture cette règle spécifique
    }
}