name: CI Jeu 1 - two ships in the night

on:
  workflow_dispatch:
  push:
    paths:
      - 'jeu-1-two-ships/**'
  pull_request:
    branches:
      - main
    paths:
      - 'jeu-1-two-ships/**'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read

jobs:
  job-build:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./jeu-1-two-ships
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5
      - name: Configuration de Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './jeu-1-two-ships/package-lock.json'
      - name: Installation des dépendances
        run: npm install

  job-audit:
    needs: job-build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./jeu-1-two-ships
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5
      - name: Configuration de Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './jeu-1-two-ships/package-lock.json'
      - name: Installation des dépendances
        run: npm install
      - name: Audit des dépendances
        run: npm audit > rapport-audit.txt
      - name: Affichage dans le résumé
        if: always()
        run: |
          echo "### Résultat brut de l'audit" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat rapport-audit.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Création de l'artefact
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: preuve-audit
          path: jeu-1-two-ships/rapport-audit.txt

  job-lint:
    needs: job-build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./jeu-1-two-ships
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5
      - name: Configuration de Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './jeu-1-two-ships/package-lock.json'
      - name: Installation des dépendances
        run: npm install
      - name: Linter
        run: npm run lint

  job-test:
    needs: job-build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./jeu-1-two-ships
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5
      - name: Configuration de Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './jeu-1-two-ships/package-lock.json'
      - name: Installation des dépendances
        run: npm install
      - name: Lancement des tests unitaires
        run: npm run test > rapport-tests.txt 2>&1
      - name: Affichage dans le résumé
        if: always()
        run: |
          echo "### Résultat brut des tests" >> $GITHUB_STEP_SUMMARY
          echo '```text' >> $GITHUB_STEP_SUMMARY
          cat rapport-tests.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - name: Création de l'artefact
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: preuve-tests
          path: jeu-1-two-ships/rapport-tests.txt

  job-test-fonctionnel:
    needs: job-build
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ./jeu-1-two-ships
    steps:
      - name: Récupération du code
        uses: actions/checkout@v5
      - name: Configuration de Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './jeu-1-two-ships/package-lock.json'
      - name: Installation des dépendances
        run: npm install
      - name: Lancement des tests e2e
        run: npx cypress run
      - name: Capture d'écran
        if: failure()
        uses: actions/upload-artifact@v5
        with:
          name: erreur-cypress
          path: jeu-1-two-ships/cypress/screenshots/

  job-summary:
    needs: [job-test, job-lint, job-audit, job-test-fonctionnel]
    if: always()
    runs-on: ubuntu-22.04
    steps:
      - name: Téléchargement de la capture
        if: needs.job-test-fonctionnel.result == 'failure'
        uses: actions/download-artifact@v5
        with:
          name: erreur-cypress
          path: image-recuperee
      - name: Génération du résumé global
        run: |
          echo "## Bilan de l'exécution" >> $GITHUB_STEP_SUMMARY
          echo "- Audit : ${{ needs.job-audit.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Linter : ${{ needs.job-lint.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests Unitaires : ${{ needs.job-test.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Tests Fonctionnels : ${{ needs.job-test-fonctionnel.result }}" >> $GITHUB_STEP_SUMMARY
          if [ -d "image-recuperee" ]; then
            echo "### Erreur visuelle détectée" >> $GITHUB_STEP_SUMMARY
            echo "Un test fonctionnel a échoué. Télécharge l'archive **erreur-cypress** dans la section *Artifacts* pour visionner la capture d'écran." >> $GITHUB_STEP_SUMMARY
          fi